// Generated by CoffeeScript 1.3.3
(function() {

  exports.run = function() {
    var args, create;
    create = require("./create");
    args = process.argv.splice(2);
    if (args[0] === "create") {
      console.log("creating app " + args[1]);
      return create({
        appName: args[1]
      });
    }
  };

}).call(this);
