// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  module.exports = function(config) {
    var createFiles, createFolder, eco, fs, mkdir, newPath, npm, path, print, spawn;
    fs = require("fs");
    path = require("path");
    eco = require("eco");
    spawn = require('child_process').spawn;
    print = require('util').print;
    mkdir = require("mkdirp");
    newPath = function(oldPath) {
      var r;
      r = oldPath.replace(__dirname + "/../templates/", "./" + config.appName + "/");
      console.log("working on " + r);
      return r;
    };
    createFolder = function(pathPrefix) {
      var file, stats, _i, _len, _ref, _results;
      _ref = fs.readdirSync(pathPrefix);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        stats = fs.lstatSync(pathPrefix + file);
        if (stats.isDirectory()) {
          createFolder(pathPrefix + file + "/");
          _results.push(mkdir.sync(newPath(pathPrefix + file)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    createFiles = function(pathPrefix) {
      var content, extension, file, filename, stats, _i, _j, _len, _ref, _ref1, _results;
      _ref = fs.readdirSync(pathPrefix);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        stats = fs.lstatSync(pathPrefix + file);
        if (stats.isDirectory()) {
          _results.push(createFiles(pathPrefix + file + "/"));
        } else {
          content = fs.readFileSync(pathPrefix + file);
          _ref1 = file.split("."), filename = 2 <= _ref1.length ? __slice.call(_ref1, 0, _j = _ref1.length - 1) : (_j = 0, []), extension = _ref1[_j++];
          if (extension === "template") {
            content = eco.render(content.toString(), config);
            filename = filename.join(".");
          } else {
            content = content.toString();
            filename = filename.join(".") + "." + extension;
          }
          _results.push(fs.writeFileSync(newPath(pathPrefix + filename), content));
        }
      }
      return _results;
    };
    createFolder(__dirname + "/../templates/");
    createFiles(__dirname + "/../templates/");
    process.chdir(config.appName);
    npm = spawn("npm", ["install"]);
    npm.stdout.on('data', function(data) {
      return print(data.toString());
    });
    npm.stderr.on("data", function(data) {
      return process.stderr.write(data.toString());
    });
    return console.log("done");
  };

}).call(this);
